/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dlyzrnwsjeegkaqwbdmp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRseXpybndzamVlZ2thcXdiZG1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0OTgwODYsImV4cCI6MjA3MTA3NDA4Nn0.IYfmfqZGjHfHma_tOHRWV62uO-oywRkGnEiI-U52xEw"